name: manage_install_example
description: "Demonstrates how to use the manage_install plugin."
publish_to: 'none'
version: 2.1.2+4

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

  manage_install:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
